### ISSUE TITLE
Any benchmarks for processing a planet PBF dump?

### ISSUE THREAD

**Issue by pablocm** [OSMNames/OSMNames#181]
Hi,
Does anyone have a rough estimate of the running time for a whole planet dump? Is it feasable to run an export on a mid-tier notebook?

Thanks.

**Comment by philippks** [comment]
hi @pablocm 

I can add some benchmarks the next days.

I wouldn't recommend running the whole planet dump on a mid-tier notebook. Processing the whole dump on server with with 500GB of ram and 40 CPUs (Intel(R) Xeon(R) Gold 6136 CPU @ 3.00GHz) takes currently up to **two days**... The imposm import of the dump into the database alone takes around 6 hours (and imposm is using all CPUs!).

With release v2.1 (not yet merged) the running times will be improved slightly. Still, there is a lot of potential for optimizations (especially in parallelizing the calculations more clever).

A simple trick to optimize the runtime would be to remove elements, you're not interested in, from the imposm import. For example if you're not interested in the housenumbers, you can remove the following lines from mapping.yml
```
    type_mappings:
      points:
        addr:housenumber:
        - __any__
      polygons:
        addr:housenumber:
        - __any__
```
Then, no housenumbers will be imported from the dump into the database.
